#ifndef ASSEMBLER_RESULTFILESHANDLER_H
#define ASSEMBLER_RESULTFILESHANDLER_H

#include "assembler.h"

#define SPACE_AND_END_LINE_LENGTH 2
#define TERMINATE_STRING_LENGTH 1
#define SPACE_STRING " "
#define END_LINE_STRING "\n"
#define INSTRUCTION_NAME_POSITION_MULTIPLIER 64
#define SOURCE_OPERAND_POSITION_MULTIPLIER 16
#define DESTINATION_OPERAND_POSITION_MULTIPLIER 4
#define INITIAL_ADDRESS 100
#define DOUBLE_REGISTERS_MULTIPLIER 64
#define OPERAND_MULTIPLIER 4
#define OPERAND_OFFSET 2
#define INSTRUCTION_ERROR (-1)
#define RELOCATABLE 10
#define EXTERNAL 01

#define OBJECT_FILE_EXTENTION ".ob"
#define ENTRY_FILE_EXTENTION ".ent"
#define EXTERN_FILE_EXTENTION ".ext"

/* Create result files */
void createResultFiles(ParsedFile *pfp);

#endif
